### ISSUE TITLE
Failed to obtain job status.

### ISSUE THREAD

**Issue by hazmup** [jdblischak/smk-simple-slurm#18]
I tried to use status monitoring by passing the `--parsable` flag and and adding either `cluster-status: status-sacct.sh` or `cluster-status: status-sacct.py`. I got the same error both times:
```shell
WorkflowError:
Failed to obtain job status. See above for error message.
  File "/users/pa22/sgkionis/mambaforge/envs/snakemake/lib/python3.11/asyncio/runners.py", line 190, in run
  File "/users/pa22/sgkionis/mambaforge/envs/snakemake/lib/python3.11/asyncio/runners.py", line 118, in run
  File "/users/pa22/sgkionis/mambaforge/envs/snakemake/lib/python3.11/asyncio/base_events.py", line 650, in run_until_complete
```

**Comment by jdblischak** [comment]
The part of the error message you copied is from Snakemake itself. As it says "See above for error message." Could you please copy-paste the full error message?

Also, as an experiment, could you please comment out the `cluster-status` field (it's not required to specify a separate file, it just handles more edge cases than the default behavior) and rerun your pipeline to see if that is working?

**Comment by hazmup** [comment]
There are no other error messages above though. I have been using it without `cluster-status` since, with no problems.

**Comment by jdblischak** [comment]
Another idea: are the scripts executable? What do you see when you run the following?

```sh
ls -l status-sacct.sh status-sacct.py
```

If they aren't executable, then you can run eg `chmod +x status-sacct.sh`, as I note [here](https://github.com/jdblischak/smk-simple-slurm/tree/main/extras#cluster-status-scripts)

**Comment by hazmup** [comment]
Yes, sorry I didn't mention this explicitly, I followed these steps as instructed

**Comment by jdblischak** [comment]
Ok, some more ideas to try:

1. Try using `status-scontrol.sh`. This uses `scontrol` instead of `sacct`
2. Try using [`slurm-status.py`](https://github.com/Snakemake-Profiles/slurm/blob/master/%7B%7Bcookiecutter.profile_name%7D%7D/slurm-status.py) from the official profile. It first tries to use `sacct` and then falls back to `scontrol`
3. Create a small test job and then run `sacct` and `scontrol` on its ID
    ```sh
    jobid=$(sbatch --parsable --wrap="sleep 30")
    sacct -j $jobid
    sacct -j "$jobid" --format State --noheader | head -n 1 | awk '{print $1}'
    scontrol -o show job $jobid
    scontrol -o show job "$jobid" | sed "s/^.*JobState\=\(\S*\).*$/\1/"
    ```

**Comment by hazmup** [comment]
Both 1. and 2. produce the same error. Idea 3. returns RUNNING state both with sacct and scontrol. Just to verify, cluster-status is a separate field in the profile config file and not an argument to sbatch directly, right?

**Comment by jdblischak** [comment]
>  Idea 3. returns RUNNING state both with sacct and scontrol.

This confirms that both `sacct` and `scontrol` are functional on your cluster, and thus it should be possible to use a status script

> Both 1. and 2. produce the same error. 

The fact that status scripts from 3 different sources all fail with the same error suggests that there is a problem with your local configuration

Here is a minimal reprex. Please run this and report if it succeeds or fails (along with the error message)

```sh
mkdir -p issue-18
cd issue-18
mkdir -p simple

cat << CONFIG > simple/config.yaml
cluster: sbatch --parsable
cluster-status: status-sacct.sh
jobs: 1
CONFIG

wget -P simple https://raw.githubusercontent.com/jdblischak/smk-simple-slurm/815fa684bcff3ecd9cc34c1695c65921dc6c3df0/extras/status-sacct.sh
chmod +x simple/status-sacct.sh

cat << SNAKE > Snakefile
rule test:
    output: "test.txt"
    shell: "touch {output}"
SNAKE

snakemake --profile simple/

cd -
rm -r issue-18
```

**Comment by hazmup** [comment]
I am required to specify at minimum the --account --partition and --job-name parameters for submission. Otherwise I get "sbatch: error: Batch job submission failed: Invalid account or account/partition combination specified" for --account or --partition missing, and if the --job-name is missing the job is sent to unavailable nodes and stays at pending status. If I add these parameters the job runs fine.

**Comment by hazmup** [comment]
> Ok, I'm assuming you added those parameters to the example simple/config.yaml
Yes.

My config file is:
```yaml
cluster:
  mkdir -p logs/{rule} &&
  sbatch
    --partition={resources.partition}
    --qos={resources.qos}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --job-name=smk-{rule}-{wildcards}
    --output=logs/{rule}/{rule}-{wildcards}-%j.out
    --error=logs/{rule}/{rule}-{wildcards}-.%j.err
    --account=pr014002_taskp
    --time={resources.time}
    --parsable
default-resources:
  - partition=<PARTITION>
  - qos=<QOS>
  - mem_mb=<MEM>
  - tmpdir=<TMPDIR>
  - time=<TIME>
max-jobs-per-second: 10
max-status-checks-per-second: 1
latency-wait: 60
jobs: 16
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True
cluster-status: slurm-status.py
```

```shell
$ ls .config/snakemake/myprofile/ -l
total 1025
-rw-r--r-- 1 sgkionis sgkionis    737 May  9 16:44 config.yaml
-rwxr-xr-x 1 sgkionis sgkionis 194362 May  8 17:42 slurm-status.py
-rwxr-xr-x 1 sgkionis sgkionis 160477 May  4 01:15 status-sacct.py
-rwxr-xr-x 1 sgkionis sgkionis 155778 May  4 01:11 status-sacct.sh
-rwxr-xr-x 1 sgkionis sgkionis 157646 May  8 17:30 status-scontrol.sh
```
