### ISSUE TITLE
Conditional log output?

### ISSUE THREAD

**Issue by JoshLoecker** [jdblischak/smk-simple-slurm#20]
Hi, I have a rule in Snakemake that doesn't have any wildcards. Other rules have a `wildcards.tissue_name` wildcard. When I use the below `config.yaml` configuration to submit jobs to slurm, I get an error that says the following

```
RuleException in rule get_screen_genomes in file /lustre/work/helikarlab/joshl/snakemake/Snakefile, line 346:
AttributeError: 'Wildcards' object has no attribute 'tissue_name', when formatting the following:
mkdir -p logs/{rule}/{wildcards.tissue_name} && sbatch --job-name=smk-{rule}-{wildcards} --account=helikarlab --cpus-per-task={threads} --output=logs/{rule}/{wildcards.tissue_name}/{rule}-{wildcards}.out --mem={resources.mem_mb} --time={resources.runtime} --parsable
```

Is there any way to set a "conditional" `--output` in the `sbatch` section? I see the conditional and dynamic resources examples, but it wasn't for the `sbatch` section

Thanks for any help!

This is my `config.yaml`

```yaml
cluster:
  mkdir -p logs/{rule}/{wildcards.tissue_name} &&
  sbatch
    --job-name=smk-{rule}-{wildcards}
    --account=helikarlab
    --cpus-per-task={threads}
    --output=logs/{rule}/{wildcards.tissue_name}/{rule}-{wildcards}.out
    --mem={resources.mem_mb}
    --time={resources.runtime}
    --parsable

cluster-cancel: scancel
cluster-cancel-nargs: 50
restart-times: 0
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
jobs: 100
printshellcmds: True
scheduler: greedy
use-conda: True
conda-frontend: mamba

```

**Comment by JoshLoecker** [comment]
Sorry for a late response, this is the earliest I've been able to work on this project. Your suggestion works great!

I only have 1 rule that does not have a "tissue_name" wildcard, so I've set the default resources as such

```yaml
default-resources:
  - tissue_name={wildcards.tissue_name}
```

And then in the rule that doesn't have a tissue name, I've set the resources as such

```
resources:
	tissue_name=""
```

Thank you for your help!


For anyone referencing this in the future, this is my final configuration file

```yaml
cluster:
  mkdir -p logs/{rule}/{resources.tissue_name} &&
  sbatch
    --job-name=smk-{rule}-{wildcards}
    --account=helikarlab
    --cpus-per-task={threads}
    --output=logs/{rule}/{resources.tissue_name}/{rule}-{wildcards}.out
    --mem={resources.mem_mb}
    --time={resources.runtime}
    --parsable

default-resources:
  - tissue_name={wildcards.tissue_name}

cluster-cancel: scancel
cluster-cancel-nargs: 50
restart-times: 0
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
jobs: 100

printshellcmds: True
scheduler: greedy

use-conda: True
conda-frontend: mamba
```
